baseURL = "http://example.org/"
languageCode = "en-us"
title = "Open Mic Tech"
disqusShortname = "openmictech"
publishDir = "docs"




[taxonomies]
	author = "authors"
  category = "categories"
  tag = "tags"

  